require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BuyEntriesController do

  # This should return the minimal set of attributes required to create a valid
  # BuyEntry. As you add validations to BuyEntry, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BuyEntriesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all buy_entries as @buy_entries" do
      buy_entry = BuyEntry.create! valid_attributes
      get :index, {}, valid_session
      assigns(:buy_entries).should eq([buy_entry])
    end
  end

  describe "GET show" do
    it "assigns the requested buy_entry as @buy_entry" do
      buy_entry = BuyEntry.create! valid_attributes
      get :show, {:id => buy_entry.to_param}, valid_session
      assigns(:buy_entry).should eq(buy_entry)
    end
  end

  describe "GET new" do
    it "assigns a new buy_entry as @buy_entry" do
      get :new, {}, valid_session
      assigns(:buy_entry).should be_a_new(BuyEntry)
    end
  end

  describe "GET edit" do
    it "assigns the requested buy_entry as @buy_entry" do
      buy_entry = BuyEntry.create! valid_attributes
      get :edit, {:id => buy_entry.to_param}, valid_session
      assigns(:buy_entry).should eq(buy_entry)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new BuyEntry" do
        expect {
          post :create, {:buy_entry => valid_attributes}, valid_session
        }.to change(BuyEntry, :count).by(1)
      end

      it "assigns a newly created buy_entry as @buy_entry" do
        post :create, {:buy_entry => valid_attributes}, valid_session
        assigns(:buy_entry).should be_a(BuyEntry)
        assigns(:buy_entry).should be_persisted
      end

      it "redirects to the created buy_entry" do
        post :create, {:buy_entry => valid_attributes}, valid_session
        response.should redirect_to(BuyEntry.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved buy_entry as @buy_entry" do
        # Trigger the behavior that occurs when invalid params are submitted
        BuyEntry.any_instance.stub(:save).and_return(false)
        post :create, {:buy_entry => {}}, valid_session
        assigns(:buy_entry).should be_a_new(BuyEntry)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        BuyEntry.any_instance.stub(:save).and_return(false)
        post :create, {:buy_entry => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested buy_entry" do
        buy_entry = BuyEntry.create! valid_attributes
        # Assuming there are no other buy_entries in the database, this
        # specifies that the BuyEntry created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        BuyEntry.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => buy_entry.to_param, :buy_entry => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested buy_entry as @buy_entry" do
        buy_entry = BuyEntry.create! valid_attributes
        put :update, {:id => buy_entry.to_param, :buy_entry => valid_attributes}, valid_session
        assigns(:buy_entry).should eq(buy_entry)
      end

      it "redirects to the buy_entry" do
        buy_entry = BuyEntry.create! valid_attributes
        put :update, {:id => buy_entry.to_param, :buy_entry => valid_attributes}, valid_session
        response.should redirect_to(buy_entry)
      end
    end

    describe "with invalid params" do
      it "assigns the buy_entry as @buy_entry" do
        buy_entry = BuyEntry.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BuyEntry.any_instance.stub(:save).and_return(false)
        put :update, {:id => buy_entry.to_param, :buy_entry => {}}, valid_session
        assigns(:buy_entry).should eq(buy_entry)
      end

      it "re-renders the 'edit' template" do
        buy_entry = BuyEntry.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BuyEntry.any_instance.stub(:save).and_return(false)
        put :update, {:id => buy_entry.to_param, :buy_entry => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested buy_entry" do
      buy_entry = BuyEntry.create! valid_attributes
      expect {
        delete :destroy, {:id => buy_entry.to_param}, valid_session
      }.to change(BuyEntry, :count).by(-1)
    end

    it "redirects to the buy_entries list" do
      buy_entry = BuyEntry.create! valid_attributes
      delete :destroy, {:id => buy_entry.to_param}, valid_session
      response.should redirect_to(buy_entries_url)
    end
  end

end
